/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diwen_android_opencv_DetectionBased */

#ifndef _Included_com_diwen_android_opencv_DetectionBased
#define _Included_com_diwen_android_opencv_DetectionBased
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diwen_android_opencv_DetectionBased
 * Method:    nativeRecognized
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_diwen_android_opencv_DetectionBased_nativeRecognized
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
